### ISSUE TITLE
Review checklist?

### ISSUE THREAD

**Issue by mkelley** [lsst-sssc/ssoforcedphot#12]
We can have review checklists get automatically added to any new pull request, which should facilitate code reviews.  An example in action: https://github.com/astropy/astropy/pull/16758#issuecomment-2245183957

Starting with something simple, how does the following look?

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the coding guidelines, e.g., generally PEP8 compliant, numpydoc formatted doc strings?
- [ ] Are tests added/updated as required?
- [ ] Are docs added/updated as required?
- [ ] Did the CI pass? If no, are the failures related?

**Comment by ijiraq** [comment]
These look like pretty reasonable criteria for acceptance.  A good place to start at least.

**Comment by mschwamb** [comment]
Looks good to me. @akoumjian any additions you recommend?

**Comment by talister** [comment]
I think it  would be good to potentially add a :

- [ ] If the tests hit external service endpoints, are they simulated/mock'ed ?

**Comment by akoumjian** [comment]
I would change it to:

[] Does the PR meet the acceptance criteria of the related ticket?
[] Is there sufficient documentation for the changes?

Linting, code coverage, are all part of the CI and CI should pass in order for the PR to be merged. Same with reviews. I guess we can put those in this list, but in my mind the automations are already there so we don't really need reflection on it.

**Comment by mkelley** [comment]
Thanks.  A revised list:

- [ ] Do the proposed changes accomplish the desired goals and meet the acceptance criteria of the related issue?
- [ ] Do the proposed changes follow the coding guidelines?
- [ ] Are tests added/updated as needed?  Are methods requiring network access mocked for offline testing?
- [ ] Is there sufficient documentation for the changes?
